services:
  mdrip:
    image: microsoft/mssql-server-linux:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "123456aA!"
      ACCEPT_EULA: "Y"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mdrip
    ports:
      - "9090:9090"
